### PR TITLE
open connection in ChunkObject when send actual data

### PR DESCRIPTION
**Pull request by vills**
This patch changes moment, when connection will be open in ChunkObject class. We should open connection just before send data to swift.

For example, if client execute something like: `dd if=/dev/urandom count=1 bs=2000M | ncftpput -f creds.txt -c -m FTP_HOST DEST_FILE;`, than, when `dd` completes, connection from ftp to swift will be timeouted.

Also, after this commit ftpcloudfs wouldn't open connections to swift before got data from clients.

### CODE REVIEW

**Comment by vills** [comment]
@chmouel, @reidrac is anybody home? ;-)

**Comment by reidrac** [comment]
I didn't have time yet to review the patch, but it is in my TODO.

Thanks for the patch!

**Comment by reidrac** [comment]
OK, I see.

Most of the time the clients start sending data just after opening the file in: https://github.com/cloudfs/ftp-cloudfs/blob/master/ftpcloudfs/fs.py#L737

I can see you point. Your code looks OK. I'm thinking that in case the token is not reused we could delay the auth too, although it is less important because the toiken TTL should be longer than the HTTP connection timeout.

I'll run some tests and I'll get back to this.

Thanks again for your contribution!

**Comment by reidrac** [comment]
Thanks again for the patch!

**Pull request merged**
